image: node:14

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - CI=true
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
      - static
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - public/
      - .cache/

test:
  stage: build
  script:
    - npm install
    - npm test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - public/
      - .cache/

pages:
  image: alpine:latest
  stage: deploy
  script:
    - echo "GitLab Pages magic happens here"
  dependencies:
    - build # Pulls in the artifacts from the build stage
  artifacts:
    paths:
      - public # Required artifact of Gitlab pages
      - static
  only:
    - master
