image: node:16.5

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - CI=true
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
      - static
      - src
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

pages:
  image: alpine:latest
  stage: deploy
  script:
    - echo "GitLab Pages magic happens here"
  dependencies:
    - build # Pulls in the artifacts from the build stage
  artifacts:
    paths:
      - public # Required artifact of Gitlab pages
  only:
    - master
